/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
module test.thrift.TestService;

import thrift.base;
import thrift.codegen.base;
import thrift.util.hashset;

import test.thrift.test_types;

interface TestService {
  void ping();
  DateTime now();
  string compliment(string name);

  enum methodMeta = [
    TMethodMeta(`compliment`, 
      [TParamMeta(`name`, 1)]
    )
  ];
}
